//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weitm.Modules.ChainTouch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favorite
    {
        public System.Guid UserId { get; set; }
        public System.Guid PropertyId { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual Property Property { get; set; }
    }
}
