//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weitm.Modules.ChainTouch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndustrialPark
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Province { get; set; }
        public string Municipal { get; set; }
        public string District { get; set; }
        public string Address { get; set; }
        public Nullable<int> EstablishedYear { get; set; }
        public Nullable<decimal> JurisdictionAreaSize { get; set; }
        public string PillarIndustry { get; set; }
        public string MncPresence { get; set; }
        public string Others { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<double> NorthLatitude { get; set; }
        public Nullable<double> EastLongitude { get; set; }
    }
}
