//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weitm.Modules.ChainTouch.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WeitmChainTouchEntities : DbContext
    {
        public WeitmChainTouchEntities()
            : base("name=WeitmChainTouchEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Developer> Developers { get; set; }
        public virtual DbSet<IndustrialPark> IndustrialParks { get; set; }
        public virtual DbSet<Picture> Pictures { get; set; }
        public virtual DbSet<Property> Properties { get; set; }
        public virtual DbSet<Favorite> Favorites { get; set; }
    }
}
